// Builds js/london-data.js: pre-projected SVG paths for the 33 London local authorities,
// the Thames, a graticule and the Prime Meridian.
//
// Source: ONS Local Authority Districts (2013), via github.com/martinjc/UK-GeoJSON
//   curl -L -o lad.json https://raw.githubusercontent.com/martinjc/UK-GeoJSON/master/json/administrative/eng/lad.json
// Usage: npm i d3-geo @turf/turf polylabel && node tools/build-map.mjs lad.json
import fs from 'fs';
import * as turf from '@turf/turf';
import {geoTransverseMercator, geoPath, geoArea} from 'd3-geo';
import polylabel from 'polylabel';

const lad = JSON.parse(fs.readFileSync(process.argv[2] || 'lad.json'));
const fc = {type: 'FeatureCollection', features: lad.features
  .filter(f => /^E09/.test(f.properties.LAD13CD))
  .map(f => ({type: 'Feature', properties: {code: f.properties.LAD13CD, name: f.properties.LAD13NM}, geometry: f.geometry}))};

// The ONS boundaries stop at the river bank, so the Thames is the gap between boroughs.
// Recover it as a polygon: morphological closing of the union, minus the union, keep the biggest piece.
const tf = turf.rewind(JSON.parse(JSON.stringify(fc)), {reverse: false});
let uni = tf.features[0];
for (const f of tf.features.slice(1)) uni = turf.union(turf.featureCollection([uni, f]));
const R = 0.55;
const closed = turf.buffer(turf.buffer(uni, R, {units: 'kilometers', steps: 16}), -R, {units: 'kilometers', steps: 16});
const gap = turf.difference(turf.featureCollection([closed, uni]));
const pieces = (gap.geometry.type === 'Polygon' ? [gap.geometry.coordinates] : gap.geometry.coordinates)
  .map(c => turf.polygon(c)).sort((a, b) => turf.area(b) - turf.area(a));
const river = turf.rewind(pieces[0], {reverse: true});

const W = 1000, H = 780;
const proj = geoTransverseMercator().rotate([0.1, -51.5]).fitExtent([[20, 20], [W - 20, H - 20]], fc);
const path = geoPath(proj);
const r2 = n => Math.round(n * 100) / 100;
const fmt = d => d.replace(/-?\d+\.\d+/g, m => String(r2(+m)));

const boroughs = fc.features.map(f => {
  const [[x0, y0], [x1, y1]] = path.bounds(f);
  const [cx, cy] = path.centroid(f);
  const polys = (f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates)
    .map(poly => poly.map(ring => ring.map(p => proj(p))));
  const ringArea = r => Math.abs(r.reduce((s, [x, y], i) => { const [u, v] = r[(i + 1) % r.length]; return s + x * v - u * y; }, 0));
  polys.sort((a, b) => ringArea(b[0]) - ringArea(a[0]));
  const lp = polylabel(polys[0], 0.5);
  return {
    code: f.properties.code, name: f.properties.name, d: fmt(path(f)),
    b: [x0, y0, x1, y1].map(r2), c: [r2(cx), r2(cy)], l: [r2(lp[0]), r2(lp[1])],
    km2: Math.round(geoArea(f) * 6371.0088 ** 2 * 10) / 10,
  };
});

// graticule (every 0.1° lon, 0.05° lat) and the Prime Meridian
const line = coords => fmt(path({type: 'LineString', coordinates: coords}));
const grat = [];
for (let lon = -0.6; lon <= 0.41; lon += 0.1) { const L = r2(lon); if (Math.abs(L) > 1e-9) grat.push(line([[L, 51.2], [L, 51.8]])); }
for (let lat = 51.25; lat <= 51.76; lat += 0.05) grat.push(line([[-0.7, lat], [0.5, lat]]));
const meridian = line([[0, 51.2], [0, 51.8]]);
const [ax] = proj([0, 51.5]), [bx] = proj([0.1, 51.5]);
const kmPx = Math.abs(bx - ax) / (0.1 * 111.32 * Math.cos(51.5 * Math.PI / 180));

const out = {w: W, h: H, kmPx: r2(kmPx), boroughs, river: fmt(path(river)), graticule: grat.join(''), meridian};
fs.writeFileSync('js/london-data.js',
  '/* Generated by tools/build-map.mjs. Contains National Statistics data © Crown copyright and database right 2013; contains OS data © Crown copyright 2013. */\n' +
  'window.LONDON=' + JSON.stringify(out) + ';\n');
console.log('wrote js/london-data.js', fs.statSync('js/london-data.js').size, 'bytes; kmPx', r2(kmPx));
